services:
  db:
    image: postgres:14.4-alpine
    restart: always
    hostname: pgdatabase
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
 
  web:
      build: .
      ports:
        - "5000:5000"
      env_file:
        - .env
      container_name: product-service
      depends_on:
        db:
          condition: service_healthy
 
volumes:
  pgdata:
