name: CICD Workflow
on:  
  push:    
    branches: 
      main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Build and Push Image to Registry
          run: |
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker build . -t pabloesdev/fastapi-app:latest
            docker push pabloesdev/fastapi-app:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Pull Image from Docker Hub
            run: |
              sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
              sudo docker pull pabloesdev/fastapi-app:latest
          - name: Run Docker Container
            run: sudo docker compose up -f ${{ github.workspace }}/pg-docker-compose.yml -d
